version: '3.5'
services: 
  web:
    image: nginx
    volumes:
      - ./Ripple-NGINX/:/etc/nginx/conf.d/
      - ./Certificates/:/src/certificates/
    links:  
      - lets
      - pep.py
      - hanayo
      - rippleapi
    depends_on:
      - lets
      - pep.py
      - hanayo
      - rippleapi
    ports: 
      - 80:80
      - 443:443
    restart: on-failure

  hanayo:
    image: hanayo
    build: ./Ripple-Hanayo
    volumes:
      - ./data/hanayo/:/ripple
      - ./data/avatars/:/avatars
    links: 
      - db
      - redis
      - rippleapi
    depends_on:
      - db
      - redis
      - rippleapi
    restart: on-failure

  rippleapi:
    image: rippleapi
    build: ./Ripple-API
    volumes:
      - ./data/rippleapi/:/ripple/
    links: 
      - db
      - redis
    depends_on:
      - db
      - redis
    restart: on-failure

  pep.py:
    image: pep.py
    build: ./Ripple-PEP.PY
    volumes:
      - ./data/pep.py/:/ripple
    links: 
      - db
      - redis
    depends_on:
      - db
      - redis
    restart: on-failure
    ports:
      - "6667:6667"

  lets:
    image: lets
    build: ./Ripple-LETS
    volumes:
      - ./data/lets/:/ripple
      - ./data/lets/common:/ripple-src/common
    links: 
      - db
      - redis
    depends_on:
      - db
      - redis
    restart: on-failure


  # Datacore
  redis:
    image: redis
    volumes:
      - ripple_redis_vol:/data
    restart: on-failure
    expose:
      - 6379

  db:
    container_name: db
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ripple_mysql_data:/var/lib/mysql
      - ./ripple.sql:/docker-entrypoint-initdb.d/ripple.sql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    expose:
      - 3306

volumes:
  ripple_mysql_data:
  ripple_redis_vol:
